import Link from 'next/link'; import {notFound} from 'next/navigation';
import {requireAdmin} from '@/lib/auth/require-admin'; import {SubmitButton} from '@/app/admin/components/submit-button'; import {editPublishedMenu,saveDraft} from '../actions';
const labels:Record<string,string>={breakfast:'Breakfast',lunch:'Lunch',evening_tea:'Evening Tea',dinner:'Dinner'};
export default async function EditMenuPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;saved?:string;cloned?:string}>}) {
  const {id}=await params; const message=await searchParams; const {supabase}=await requireAdmin();
  const {data:menu}=await supabase.from('menu_weeks').select('id,week_start,status,verified_at,meals(id,date,meal_type,start_time,end_time,notes,sort_order,menu_items(name,sort_order))').eq('id',id).maybeSingle(); if(!menu)notFound();
  const meals=[...menu.meals].sort((a,b)=>a.date.localeCompare(b.date)||a.sort_order-b.sort_order); const editable=menu.status==='draft';
  return <main className="admin-page wide"><div className="admin-page-head"><div><p className="eyebrow">ADMIN / DRAFT EDITOR</p><h1>Week of {menu.week_start}</h1><p>{editable?'Add one food item per line. Saving invalidates earlier verification.':'Published menus are read-only. Create a private draft to make changes.'}</p></div><div className="menu-row-actions"><Link className="secondary-button" href={`/admin/menu/${id}/preview`}>PREVIEW</Link>{!editable&&<form action={editPublishedMenu.bind(null,id)}><SubmitButton>EDIT AS DRAFT</SubmitButton></form>}</div></div>{message.error&&<p className="admin-alert error" role="alert">{message.error}</p>}{message.cloned&&<p className="admin-alert success" role="status">Private edit draft created. Students still see the published menu.</p>}{message.saved&&<p className="admin-alert success" role="status">Draft saved. Review the preview before verification.</p>}<form action={saveDraft.bind(null,id)} className="menu-editor">{meals.map((meal,index)=>{const dayHeading=index===0||meals[index-1].date!==meal.date;const items=[...meal.menu_items].sort((a,b)=>a.sort_order-b.sort_order).map(i=>i.name).join('\n');return <div key={meal.id} className="meal-editor-wrap">{dayHeading&&<h2>{new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(`${meal.date}T00:00:00Z`))}</h2>}<fieldset className="meal-editor" disabled={!editable}><legend>{labels[meal.meal_type]}</legend><div className="time-fields"><label>Starts<input name={`start_${meal.id}`} type="time" defaultValue={meal.start_time.slice(0,5)} required/></label><label>Ends<input name={`end_${meal.id}`} type="time" defaultValue={meal.end_time.slice(0,5)} required/></label></div><label>Food items<textarea name={`items_${meal.id}`} rows={4} defaultValue={items} placeholder={'Poha\nTea\nBanana'}/></label><label>Notes <span>(optional)</span><input name={`notes_${meal.id}`} maxLength={500} defaultValue={meal.notes??''}/></label></fieldset></div>})}{editable&&<div className="editor-actions"><SubmitButton>SAVE DRAFT</SubmitButton><Link className="secondary-button" href={`/admin/menu/${id}/preview`}>REVIEW PREVIEW</Link></div>}</form></main>;
}
